name: Into the Wild Kennels
favicon: null
layout_spectrum: 0.99889
typography_spectrum: 0.74778
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#080808'
    - '#3a3b2d'
    - '#889f4c'
    - '#b4ca81'
    - '#d7f6a9'
  brandStrength: 0.25
  lightness: 0.5
  saturation: 0.625
  rhythmicContrast: 0.75
purpose: []
