name: Into the Wild Kennels
favicon: null
layout_spectrum: 0.99889
typography_spectrum: 0.49459
title: Into the Wild Kennels
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#0d0d0d'
    - '#b7d9fe'
    - '#5c7088'
    - '#293144'
    - '#bea086'
  brandStrength: 0.25
  lightness: 0.5
  saturation: 0.625
  rhythmicContrast: 0.75
purpose: []
